// Generated by scripts/generate-pet-sprites.mjs — do not edit by hand.
// Regenerate with: node src/web/scripts/generate-pet-sprites.mjs

// Sheet geometry: 32x32 px grid at 4x scale, 4 eye frames per strip.
export const PET_SPRITE_COLS = 8;
export const PET_SPRITE_ROW_COUNT = 25;

export type PetSpriteRowId =
  | "idle"
  | "walk"
  | "sleep"
  | "sleepDeep"
  | "doze"
  | "wake"
  | "shock"
  | "shaken"
  | "faint"
  | "think"
  | "code"
  | "read"
  | "phone"
  | "build"
  | "juggle"
  | "cheer"
  | "alert"
  | "carry"
  | "sweep"
  | "snack"
  | "bell"
  | "type"
  | "walkRead"
  | "walkPhone"
  | "walkSnack";

export type PetSpriteRow = {
  id: PetSpriteRowId;
  index: number;
  frames: number;
  frameMs: number;
  eyes: "overlay" | "baked";
};

export const PET_SPRITE_ROWS: readonly PetSpriteRow[] = [
  {
    "id": "idle",
    "index": 0,
    "frames": 1,
    "frameMs": 1000,
    "eyes": "overlay"
  },
  {
    "id": "walk",
    "index": 1,
    "frames": 4,
    "frameMs": 110,
    "eyes": "overlay"
  },
  {
    "id": "sleep",
    "index": 2,
    "frames": 4,
    "frameMs": 700,
    "eyes": "baked"
  },
  {
    "id": "sleepDeep",
    "index": 3,
    "frames": 2,
    "frameMs": 1100,
    "eyes": "baked"
  },
  {
    "id": "doze",
    "index": 4,
    "frames": 2,
    "frameMs": 650,
    "eyes": "baked"
  },
  {
    "id": "wake",
    "index": 5,
    "frames": 2,
    "frameMs": 420,
    "eyes": "baked"
  },
  {
    "id": "shock",
    "index": 6,
    "frames": 2,
    "frameMs": 170,
    "eyes": "baked"
  },
  {
    "id": "shaken",
    "index": 7,
    "frames": 2,
    "frameMs": 90,
    "eyes": "baked"
  },
  {
    "id": "faint",
    "index": 8,
    "frames": 2,
    "frameMs": 900,
    "eyes": "baked"
  },
  {
    "id": "think",
    "index": 9,
    "frames": 4,
    "frameMs": 430,
    "eyes": "overlay"
  },
  {
    "id": "code",
    "index": 10,
    "frames": 4,
    "frameMs": 200,
    "eyes": "overlay"
  },
  {
    "id": "read",
    "index": 11,
    "frames": 4,
    "frameMs": 650,
    "eyes": "overlay"
  },
  {
    "id": "phone",
    "index": 12,
    "frames": 4,
    "frameMs": 480,
    "eyes": "overlay"
  },
  {
    "id": "build",
    "index": 13,
    "frames": 4,
    "frameMs": 300,
    "eyes": "overlay"
  },
  {
    "id": "juggle",
    "index": 14,
    "frames": 4,
    "frameMs": 160,
    "eyes": "overlay"
  },
  {
    "id": "cheer",
    "index": 15,
    "frames": 4,
    "frameMs": 210,
    "eyes": "overlay"
  },
  {
    "id": "alert",
    "index": 16,
    "frames": 2,
    "frameMs": 260,
    "eyes": "overlay"
  },
  {
    "id": "carry",
    "index": 17,
    "frames": 2,
    "frameMs": 420,
    "eyes": "overlay"
  },
  {
    "id": "sweep",
    "index": 18,
    "frames": 4,
    "frameMs": 230,
    "eyes": "overlay"
  },
  {
    "id": "snack",
    "index": 19,
    "frames": 4,
    "frameMs": 340,
    "eyes": "overlay"
  },
  {
    "id": "bell",
    "index": 20,
    "frames": 2,
    "frameMs": 300,
    "eyes": "overlay"
  },
  {
    "id": "type",
    "index": 21,
    "frames": 4,
    "frameMs": 180,
    "eyes": "overlay"
  },
  {
    "id": "walkRead",
    "index": 22,
    "frames": 4,
    "frameMs": 110,
    "eyes": "overlay"
  },
  {
    "id": "walkPhone",
    "index": 23,
    "frames": 4,
    "frameMs": 110,
    "eyes": "overlay"
  },
  {
    "id": "walkSnack",
    "index": 24,
    "frames": 4,
    "frameMs": 110,
    "eyes": "overlay"
  }
] as const;

export const PET_SPRITE_ROW_BY_ID: ReadonlyMap<PetSpriteRowId, PetSpriteRow> = new Map(
  PET_SPRITE_ROWS.map((row) => [row.id, row])
);

export function petSpriteBodyUrl(presetId: string) {
  return `/pets/${presetId}.png`;
}

export function petSpriteEyesUrl(presetId: string) {
  return `/pets/${presetId}-eyes.png`;
}
