import type { CSSProperties } from "react";

import styles from "./cloud-code-monster-pet.module.css";

import type {
  CloudCodeMonsterActivityId,
  CloudCodeMonsterPetPreset,
  PetPoint,
} from "./cloud-code-monster-pet-types";
import {
  PET_SPRITE_COLS,
  PET_SPRITE_ROW_BY_ID,
  PET_SPRITE_ROW_COUNT,
  PET_SPRITE_ROWS,
  petSpriteBodyUrl,
  petSpriteEyesUrl,
  type PetSpriteRowId,
} from "./cloud-code-monster-pet-sprite-manifest";

/** viewBox px (legacy SVG coordinate space) -> displayed px at the 82px pet size */
const VIEWBOX_TO_DISPLAY = 82 / 128;
const EMPTY_EYE_OFFSET: PetPoint = { x: 0, y: 0 };

type PetPreviewBounds = {
  left: number;
  top: number;
  width: number;
  height: number;
};

function roundToQuarter(value: number) {
  return Math.round(value * 4) / 4;
}

/**
 * Maps the pet state machine onto a sprite-sheet row. Texture keyframes for
 * every row are generated by scripts/generate-pet-sprites.mjs.
 */
export function resolvePetSpriteRowId(
  activityId: CloudCodeMonsterActivityId | null,
  options: {
    reacting?: boolean;
    shaken?: boolean;
    fainted?: boolean;
    walking?: boolean;
    deepSleeping?: boolean;
  } = {}
): PetSpriteRowId {
  if (options.fainted) {
    return "faint";
  }

  if (options.shaken) {
    return "shaken";
  }

  if (options.reacting) {
    return "shock";
  }

  if (options.walking) {
    if (activityId === "reading") return "walkRead";
    if (activityId === "phone") return "walkPhone";
    if (activityId === "snacking") return "walkSnack";
    return "walk";
  }

  switch (activityId) {
    case "sleeping":
      // snore for the first stretch, then settle into motionless deep sleep
      return options.deepSleeping ? "sleepDeep" : "sleep";
    case "dozing":
    case "yawning":
      return "doze";
    case "waking":
      return "wake";
    case "thinking":
      return "think";
    case "coding":
      return "code";
    case "reading":
      return "read";
    case "phone":
      return "phone";
    case "building":
      return "build";
    case "juggling":
      return "juggle";
    case "attention":
      return "cheer";
    case "error":
      return "alert";
    case "carrying":
      return "carry";
    case "sweeping":
      return "sweep";
    case "snacking":
      return "snack";
    case "notification":
      return "bell";
    case "typing":
      return "type";
    default:
      return "idle";
  }
}

function resolveEyeVariant(rowId: PetSpriteRowId): "blink" | "happy" {
  return rowId === "cheer" || rowId === "juggle" ? "happy" : "blink";
}

export function clampMonsterSpriteEyeOffset(
  eyeOffset: { x: number; y: number },
  preset: CloudCodeMonsterPetPreset
) {
  const max = preset.eyeOffsetMax;
  if (!max) return eyeOffset;

  return {
    x: Math.max(-max.x, Math.min(max.x, eyeOffset.x)),
    y: Math.max(-max.y, Math.min(max.y, eyeOffset.y)),
  };
}

export function resolveCloudCodeMonsterPreviewEyeOffset(
  pointer: PetPoint,
  bounds: PetPreviewBounds,
  preset: CloudCodeMonsterPetPreset
): PetPoint {
  if (
    !Number.isFinite(pointer.x) ||
    !Number.isFinite(pointer.y) ||
    !Number.isFinite(bounds.left) ||
    !Number.isFinite(bounds.top) ||
    !Number.isFinite(bounds.width) ||
    !Number.isFinite(bounds.height) ||
    bounds.width <= 0 ||
    bounds.height <= 0
  ) {
    return EMPTY_EYE_OFFSET;
  }

  const centerX = bounds.left + bounds.width / 2;
  const centerY = bounds.top + bounds.height / 2;
  const deltaX = pointer.x - centerX;
  const deltaY = pointer.y - centerY;
  const distance = Math.hypot(deltaX, deltaY);
  const radius = Math.max(1, Math.min(bounds.width, bounds.height) * 0.48);

  if (distance <= radius * 0.08) {
    return EMPTY_EYE_OFFSET;
  }

  const pull = Math.min(1, distance / radius);
  const rawEyeOffset = {
    x: roundToQuarter((deltaX / distance) * 5.5 * pull),
    y: roundToQuarter((deltaY / distance) * 4 * pull),
  };

  return clampMonsterSpriteEyeOffset(rawEyeOffset, preset);
}

function rowPositionY(rowIndex: number) {
  return `${((rowIndex / (PET_SPRITE_ROW_COUNT - 1)) * 100).toFixed(4)}%`;
}

export type MonsterSpriteProps = {
  activityId: CloudCodeMonsterActivityId | null;
  preset: CloudCodeMonsterPetPreset;
  reacting?: boolean;
  shaken?: boolean;
  fainted?: boolean;
  walking?: boolean;
  deepSleeping?: boolean;
  eyeOffset?: { x: number; y: number };
  withShadow?: boolean;
};

/**
 * Texture-based pet renderer. The body plays generated sprite-sheet keyframes
 * via steps() animations; the eyes live on a separate texture overlay so they
 * can keep blinking *and* track the cursor continuously.
 */
export function MonsterSprite({
  activityId,
  preset,
  reacting = false,
  shaken = false,
  fainted = false,
  walking = false,
  deepSleeping = false,
  eyeOffset = { x: 0, y: 0 },
  withShadow = true,
}: MonsterSpriteProps) {
  const rowId = resolvePetSpriteRowId(activityId, {
    reacting,
    shaken,
    fainted,
    walking,
    deepSleeping,
  });
  const row = PET_SPRITE_ROW_BY_ID.get(rowId) ?? PET_SPRITE_ROWS[0]!;
  const bodyStyle = {
    backgroundImage: `url(${petSpriteBodyUrl(preset.id)})`,
    backgroundSize: `${PET_SPRITE_COLS * 100}% ${PET_SPRITE_ROW_COUNT * 100}%`,
    "--monster-sprite-row-y": rowPositionY(row.index),
    "--monster-sprite-cycle-ms": `${row.frames * row.frameMs}ms`,
  } as CSSProperties;
  const clampedEyeOffset = clampMonsterSpriteEyeOffset(eyeOffset, preset);
  const eyesStyle = {
    backgroundImage: `url(${petSpriteEyesUrl(preset.id)})`,
    "--monster-eye-x": `${(clampedEyeOffset.x * VIEWBOX_TO_DISPLAY).toFixed(2)}px`,
    "--monster-eye-y": `${(clampedEyeOffset.y * VIEWBOX_TO_DISPLAY).toFixed(2)}px`,
  } as CSSProperties;

  return (
    <span className={styles.sprite} data-sprite-row={rowId} aria-hidden="true">
      {withShadow ? <span className={styles.spriteShadow} /> : null}
      <span className={styles.spriteCharacter}>
        <span
          className={styles.spriteSheet}
          data-frames={row.frames}
          style={bodyStyle}
        />
        {row.eyes === "overlay" ? (
          <span
            className={styles.spriteEyes}
            data-variant={resolveEyeVariant(rowId)}
            style={eyesStyle}
          />
        ) : null}
      </span>
    </span>
  );
}

/** Animated preset preview used by the settings Pet tab. */
export function CloudCodeMonsterPresetPreview({
  preset,
  eyeOffset = EMPTY_EYE_OFFSET,
  className,
}: {
  preset: CloudCodeMonsterPetPreset;
  eyeOffset?: PetPoint;
  className?: string;
}) {
  return (
    <span
      role="img"
      aria-label={`${preset.name} pixel PET preset`}
      className={`${styles.spritePreview}${className ? ` ${className}` : ""}`}
    >
      <MonsterSprite activityId={null} preset={preset} eyeOffset={eyeOffset} />
    </span>
  );
}
