packages:
  - "src/shared"
  - "src/cli"
  - "src/web"
  - "src/email-worker"
  - "src/ws-do"
  - "src/app"

allowBuilds:
  esbuild: true
  msw: true
  sharp: true
  simple-git-hooks: true
  unrs-resolver: true
  workerd: true
