import { beforeEach, afterEach, describe, expect, it, vi } from "vitest"
import { act, fireEvent } from "@/test/react-dom-harness"
import { bodyTop, installMessageScrollFixture, restoreMessageScrollFixture, message, mount, runFrames, scrollFixture } from "@/test/message-scroll-fixture"

beforeEach(installMessageScrollFixture)
afterEach(restoreMessageScrollFixture)

describe("native pagination and original semantic epoch", () => {
  it("restores initial New intent and bounded settling after StrictMode effect replay", () => {
    const shown = vi.fn()
    const items = Array.from({ length: 14 }, (_, i) => ({ ...message(`m${i}`), newDivider: i === 4 }))
    const h = mount({ items, newDividerBefore: "m4", onInitialPositionSettled: shown }, true)
    const marker = h.root.querySelector('[data-new-divider]')!.getBoundingClientRect()
    expect((marker.top + marker.bottom) / 2).toBeCloseTo(scrollFixture.height / 2, 0)
    expect(scrollFixture.latest.readPositionReady).toBe(true)
    expect(shown).toHaveBeenCalledOnce()
  })
  it("restores an explicit target after StrictMode replay and consumes only its current proof", () => {
    const consumed = vi.fn()
    const h = mount({ scrollToMessageId: "m4", onScrollTargetPositioned: consumed }, true)
    expect(consumed).toHaveBeenCalledExactlyOnceWith("m4")
    expect(scrollFixture.latest.readPositionReady).toBe(true)
    expect(bodyTop(h.root, "m4")).toBeGreaterThanOrEqual(0)
    expect(bodyTop(h.root, "m4")).toBeLessThan(scrollFixture.height)
  })
  it("rebinds a pending Present requested by a layout consumer across StrictMode replay", () => {
    let requested = false
    const h = mount({ hasMoreNewer: true }, true, result => {
      if (requested) return
      requested = true
      result.requestPresentPosition()
    })
    expect(scrollFixture.latest.readPositionReady).toBe(false)
    const end = vi.spyOn(scrollFixture.latest.virtualizer, "scrollToEnd")
    h.update({ hasMoreNewer: false, presentVersion: 1, items: [...h.input.items, message("current-tail")] })
    expect(end).toHaveBeenCalledOnce()
    expect(scrollFixture.latest.readPositionReady).toBe(true)
    expect(h.root.scrollTop).toBe(h.root.scrollHeight - scrollFixture.height)
  })
  it("uses native same-key preservation for newer append and head trim", () => {
    const h = mount()
    h.move(650)
    const before = bodyTop(h.root, "m7")
    const offset = vi.spyOn(scrollFixture.latest.virtualizer, "scrollToOffset")
    const index = vi.spyOn(scrollFixture.latest.virtualizer, "scrollToIndex")
    act(() => scrollFixture.latest.captureNewerPageAnchor())
    h.update({ isFetchingNewer: true })
    h.update({ items: [...h.input.items.slice(2), message("newer1"), message("newer2")], isFetchingNewer: false })
    expect(bodyTop(h.root, "m7")).toBeCloseTo(before, 0)
    expect(offset).not.toHaveBeenCalled()
    expect(index).not.toHaveBeenCalled()
    expect(scrollFixture.latest.isNewerPageAnchorSettling).toBe(false)
  })
  it("does not treat a divider update as observed fetch completion", () => {
    const h = mount()
    act(() => scrollFixture.latest.captureOlderPageAnchor())
    h.update({ items: [...h.input.items] })
    expect(scrollFixture.latest.isOlderPageAnchorSettling).toBe(true)
    h.update({ isFetchingOlder: true })
    h.update({ isFetchingOlder: false })
    expect(scrollFixture.latest.isOlderPageAnchorSettling).toBe(false)
  })
  it("finishes a replacement window without inventing preservation of a removed key or following its historical tail", () => {
    const h = mount({ viewerUserId: "me" })
    h.move(500)
    const end = vi.spyOn(scrollFixture.latest.virtualizer, "scrollToEnd")
    act(() => scrollFixture.latest.captureNewerPageAnchor())
    h.update({ isFetchingNewer: true })
    h.update({ items: Array.from({ length: 12 }, (_, i) => message(`replacement${i}`, "me")), isFetchingNewer: false })
    expect(scrollFixture.latest.isNewerPageAnchorSettling).toBe(false)
    expect(h.root.querySelector('[data-msg-id="m5"]')).toBeNull()
    expect(end).not.toHaveBeenCalled()
  })
  it("keeps the original initial New intent while an older page moves its numeric index", () => {
    const items = Array.from({ length: 14 }, (_, i) => ({ ...message(`m${i}`), newDivider: i === 4 }))
    const h = mount({ items, newDividerBefore: "m4", initialScrollReady: false, hasMoreNewer: true })
    act(() => scrollFixture.latest.captureOlderPageAnchor())
    h.update({ isFetchingOlder: true })
    h.update({ items: [message("older"), ...h.input.items], isFetchingOlder: false, initialScrollReady: true })
    const marker = h.root.querySelector('[data-new-divider]')!.getBoundingClientRect()
    expect((marker.top + marker.bottom) / 2).toBeCloseTo(scrollFixture.height / 2, 0)
    expect(scrollFixture.latest.readPositionReady).toBe(true)
  })
  it("retires the old native index once on replacement and rejects its canceled frame", () => {
    const consumed = vi.fn()
    const h = mount({ onScrollTargetPositioned: consumed })
    h.stage({ scrollToMessageId: "m12" })
    const stale = [...scrollFixture.frames.values()]
    const offset = vi.spyOn(scrollFixture.latest.virtualizer, "scrollToOffset")
    h.stage({ scrollToMessageId: "unloaded" })
    expect(offset).toHaveBeenCalledTimes(1)
    act(() => stale.forEach(callback => callback(performance.now())))
    expect(consumed).not.toHaveBeenCalled()
    h.update({ items: [...h.input.items, message("unloaded")] })
    expect(consumed).toHaveBeenCalledExactlyOnceWith("unloaded")
  })
  it("cancels an owned native index on user takeover without canceling ordinary native compensation", () => {
    const h = mount()
    h.stage({ scrollToMessageId: "m12" })
    const offset = vi.spyOn(scrollFixture.latest.virtualizer, "scrollToOffset")
    fireEvent.wheel(h.root, { deltaY: -20 })
    expect(offset).toHaveBeenCalledTimes(1)
    runFrames()
    offset.mockClear()
    fireEvent.wheel(h.root, { deltaY: -20 })
    runFrames()
    expect(offset).not.toHaveBeenCalled()
  })
  it("does not consume a previously completed external target when canceling a local reply jump", () => {
    const consumed = vi.fn()
    const cancelled = vi.fn()
    const h = mount({ onScrollTargetPositioned: consumed, onScrollTargetCancelled: cancelled })
    h.update({ scrollToMessageId: "m4" })
    expect(consumed).toHaveBeenCalledExactlyOnceWith("m4")
    act(() => scrollFixture.latest.jumpTo("m10", "auto"))
    expect(scrollFixture.latest.readPositionReady).toBe(false)
    fireEvent.wheel(h.root, { deltaY: -20 })
    runFrames()
    expect(cancelled).not.toHaveBeenCalled()
    expect(consumed).toHaveBeenCalledOnce()
  })
  it("retires pending frames and target callbacks on actual unmount", () => {
    const consumed = vi.fn()
    const shown = vi.fn()
    const h = mount({ onScrollTargetPositioned: consumed, onInitialPositionSettled: shown })
    shown.mockClear()
    h.stage({ scrollToMessageId: "m12" })
    const stale = [...scrollFixture.frames.values()]
    h.view.unmount()
    act(() => stale.forEach(callback => callback(performance.now())))
    act(() => vi.advanceTimersByTime(2500))
    expect(consumed).not.toHaveBeenCalled()
    expect(shown).not.toHaveBeenCalled()
  })
  it("retires an unsettled native end request on user takeover before late tail measurements", () => {
    const h = mount()
    const offset = vi.spyOn(scrollFixture.latest.virtualizer, "scrollToOffset")
    act(() => scrollFixture.latest.scrollToBottom())
    fireEvent.wheel(h.root, { deltaY: -20 })
    expect(offset).toHaveBeenCalledOnce()
    act(() => h.root.scrollTo({ top: 300 }))
    runFrames()
    scrollFixture.bodyHeights.set("m13", 240)
    h.update({ items: [...h.input.items] })
    expect(h.root.scrollTop).toBe(300)
    expect(offset).toHaveBeenCalledOnce()
  })
  it("replaces an unsettled native end request immediately while the new target is absent", () => {
    const h = mount()
    const offset = vi.spyOn(scrollFixture.latest.virtualizer, "scrollToOffset")
    act(() => scrollFixture.latest.scrollToBottom())
    h.stage({ scrollToMessageId: "unloaded" })
    const before = h.root.scrollTop
    expect(offset).toHaveBeenCalledOnce()
    scrollFixture.bodyHeights.set("m13", 240)
    h.update({ items: [...h.input.items] })
    expect(h.root.scrollTop).toBe(before)
    expect(offset).toHaveBeenCalledOnce()
    expect(scrollFixture.latest.readPositionReady).toBe(false)
  })
  it("waits for an absent explicit target, closes read, and finishes through its finite deadline", () => {
    const consumed = vi.fn()
    const h = mount({ onScrollTargetPositioned: consumed })
    h.update({ scrollToMessageId: "not-loaded" })
    expect(scrollFixture.latest.readPositionReady).toBe(false)
    expect(consumed).not.toHaveBeenCalled()
    act(() => vi.advanceTimersByTime(2000))
    expect(scrollFixture.latest.readPositionReady).toBe(false)
    h.update({ items: [...h.input.items, message("not-loaded")] })
    expect(consumed).not.toHaveBeenCalled()
  })
  it("opens an explicit target only after its actual body geometry and ignores target data arriving after user takeover", () => {
    const consumed = vi.fn()
    const h = mount({ onScrollTargetPositioned: consumed })
    h.update({ scrollToMessageId: "m4" })
    expect(consumed).toHaveBeenCalledWith("m4")
    expect(scrollFixture.latest.readPositionReady).toBe(true)
    h.update({ scrollToMessageId: "unloaded" })
    fireEvent.wheel(h.root, { deltaY: -20 })
    runFrames()
    h.update({ items: [...h.input.items, message("unloaded")] })
    expect(consumed).toHaveBeenCalledTimes(1)
  })
})
