import { beforeEach, afterEach, describe, expect, it, vi } from "vitest"
import { act, fireEvent } from "@/test/react-dom-harness"
import { bodyTop, installMessageScrollFixture, restoreMessageScrollFixture, message, mount, resize, runFrames, scrollFixture } from "@/test/message-scroll-fixture"

beforeEach(installMessageScrollFixture)
afterEach(restoreMessageScrollFixture)

describe("locked native adapter and existing message scroll owner", () => {
  it("unifies native total and DOM max while keeping 40/48px rail clearance", () => {
    const h = mount()
    expect(scrollFixture.latest.readPositionReady).toBe(true)
    expect(scrollFixture.latest.virtualizer.options).toMatchObject({ anchorTo: "end", followOnAppend: false, scrollEndThreshold: 1, scrollMargin: 0, paddingEnd: 48 })
    expect(h.root.scrollHeight).toBe(scrollFixture.latest.virtualizer.getTotalSize())
    expect(h.root.scrollTop).toBe(h.root.scrollHeight - scrollFixture.height)
    h.update({ tailPaddingEnd: 40 })
    expect(h.root.scrollHeight).toBe(scrollFixture.latest.virtualizer.getTotalSize())
  })
  it("centers the actual New prefix of a long message with one business correction", () => {
    scrollFixture.bodyHeights.set("m4", 1800)
    const items = Array.from({ length: 12 }, (_, i) => ({ ...message(`m${i}`), ...(i === 4 ? { newDivider: true } : {}) }))
    const h = mount({ items, newDividerBefore: "m4", hasMoreNewer: true })
    const marker = h.root.querySelector('[data-new-divider]')!.getBoundingClientRect()
    expect((marker.top + marker.bottom) / 2).toBeCloseTo(scrollFixture.height / 2, 0)
    expect(bodyTop(h.root, "m4")).toBeLessThan(scrollFixture.height)
    expect(scrollFixture.latest.readPositionReady).toBe(true)
  })
  it("clamps a first-row merged date/New boundary to the actual content origin", () => {
    scrollFixture.firstPrefix = 152
    scrollFixture.bodyHeights.set("first", 1800)
    const item = { ...message("first"), dateLabel: "Today", newDivider: true }
    const h = mount({ items: [item], hasMoreOlder: false, newDividerBefore: "first" })
    const marker = h.root.querySelector('[data-new-divider]')!.getBoundingClientRect()
    expect(h.root.scrollTop).toBe(0)
    expect(marker.top).toBeGreaterThanOrEqual(0)
    expect(marker.bottom).toBeLessThan(scrollFixture.height)
    expect(bodyTop(h.root, "first")).toBeLessThan(scrollFixture.height)
    expect(scrollFixture.latest.readPositionReady).toBe(true)
  })
  it("shows after the original deadline while keeping read and peer follow closed", () => {
    const shown = vi.fn()
    const h = mount({ initialScrollReady: false, hasMoreNewer: true, onInitialPositionSettled: shown })
    act(() => vi.advanceTimersByTime(2000))
    runFrames()
    expect(shown).toHaveBeenCalledOnce()
    expect(scrollFixture.latest.readPositionReady).toBe(false)
    expect(scrollFixture.latest.virtualizer.options.anchorTo).toBe("start")
    const before = h.root.scrollTop
    h.update({ items: [...h.input.items, message("late-peer")] })
    expect(h.root.scrollTop).toBe(before)
    expect(scrollFixture.latest.readPositionReady).toBe(false)
    h.move(300)
    expect(scrollFixture.latest.readPositionReady).toBe(true)
  })
  it("does not let pagination retire an unresolved initial intent or its deadline", () => {
    const shown = vi.fn()
    const h = mount({ initialScrollReady: false, hasMoreNewer: true, onInitialPositionSettled: shown })
    act(() => scrollFixture.latest.captureOlderPageAnchor())
    h.update({ isFetchingOlder: true })
    h.update({ isFetchingOlder: false })
    expect(scrollFixture.latest.virtualizer.options.anchorTo).toBe("start")
    act(() => vi.advanceTimersByTime(2000))
    expect(shown).toHaveBeenCalledOnce()
    expect(scrollFixture.latest.readPositionReady).toBe(false)
  })
  it("uses stable native keys for ordinary prepend without a business index restore", () => {
    const h = mount()
    h.move(500)
    const top = bodyTop(h.root, "m5")
    const index = vi.spyOn(scrollFixture.latest.virtualizer, "scrollToIndex")
    const offset = vi.spyOn(scrollFixture.latest.virtualizer, "scrollToOffset")
    act(() => scrollFixture.latest.captureOlderPageAnchor())
    h.update({ isFetchingOlder: true })
    h.update({ items: [message("older"), ...h.input.items], isFetchingOlder: false })
    expect(bodyTop(h.root, "m5")).toBeCloseTo(top, 0)
    expect(index).not.toHaveBeenCalled()
    expect(offset).not.toHaveBeenCalled()
    expect(scrollFixture.latest.isOlderPageAnchorSettling).toBe(false)
  })
  it("repairs only the current message prefix when an old first row loses its header", () => {
    scrollFixture.bodyHeights.set("m0", 1200)
    const h = mount()
    h.move(400)
    const top = bodyTop(h.root, "m0")
    const offset = vi.spyOn(scrollFixture.latest.virtualizer, "scrollToOffset")
    h.update({ items: [message("older"), ...h.input.items] })
    expect(bodyTop(h.root, "m0")).toBeCloseTo(top, 0)
    expect(offset).toHaveBeenCalledTimes(1)
  })
  it.each(["wheel", "programmatic"])("retains the current first-row body when prepend finishes before %s scroll quiet", input => {
    scrollFixture.bodyHeights.set("m0", 1200)
    const h = mount()
    if (input === "wheel") fireEvent.wheel(h.root, { deltaY: -20 })
    act(() => h.root.scrollTo({ top: 400 }))
    runFrames(2)
    const top = bodyTop(h.root, "m0")
    const offset = vi.spyOn(scrollFixture.latest.virtualizer, "scrollToOffset")
    act(() => scrollFixture.latest.captureOlderPageAnchor())
    h.stage({ isFetchingOlder: true })
    h.update({ items: [message("older"), ...h.input.items], isFetchingOlder: false })
    expect(bodyTop(h.root, "m0")).toBeCloseTo(top, 0)
    expect(offset).toHaveBeenCalledOnce()
  })
  it.each(["peer", "me"])("follows a genuine %s append through later native tail measurement", author => {
    const h = mount({ viewerUserId: "me" })
    const top = author === "peer" ? h.root.scrollHeight - scrollFixture.height : 400
    h.move(top)
    h.stage({ items: [...h.input.items, message("new-tail", author)] })
    runFrames(2)
    scrollFixture.bodyHeights.set("new-tail", 456)
    resize()
    expect(h.root.scrollHeight - h.root.clientHeight - h.root.scrollTop).toBeLessThanOrEqual(1)
    expect(scrollFixture.latest.readPositionReady).toBe(true)
  })
  it.each(["peer", "me"])("keeps a pending %s end intent on the current tail when another row arrives", author => {
    const h = mount({ viewerUserId: "me" })
    h.move(author === "peer" ? h.root.scrollHeight - scrollFixture.height : 400)
    h.stage({ items: [...h.input.items, message("first-tail", author)] })
    h.stage({ items: [...h.input.items, message("second-tail", author)] })
    resize()
    expect(h.root.scrollHeight - h.root.clientHeight - h.root.scrollTop).toBeLessThanOrEqual(1)
    expect(scrollFixture.latest.readPositionReady).toBe(true)
  })
  it("keeps a pending end intent on the current tail after history is prepended", () => {
    const h = mount({ viewerUserId: "me" })
    h.move(400)
    h.stage({ items: [...h.input.items, message("self-tail", "me")] })
    h.stage({ items: [message("older-one"), message("older-two"), ...h.input.items] })
    resize()
    expect(h.root.scrollHeight - h.root.clientHeight - h.root.scrollTop).toBeLessThanOrEqual(1)
    expect(scrollFixture.latest.readPositionReady).toBe(true)
  })
  it("does not duplicate native growth above the fold", () => {
    const h = mount()
    h.move(500)
    const top = bodyTop(h.root, "m5")
    const offset = vi.spyOn(scrollFixture.latest.virtualizer, "scrollToOffset")
    scrollFixture.bodyHeights.set("m0", 220)
    resize()
    expect(bodyTop(h.root, "m5")).toBeCloseTo(top, 0)
    expect(offset).not.toHaveBeenCalled()
  })
  it("settles same-anchor hero growth once after native layout", () => {
    scrollFixture.bodyHeights.set("m0", 1200)
    const h = mount()
    h.move(400)
    const top = bodyTop(h.root, "m0")
    const offset = vi.spyOn(scrollFixture.latest.virtualizer, "scrollToOffset")
    scrollFixture.firstPrefix += 40
    h.update({ items: [...h.input.items] })
    expect(bodyTop(h.root, "m0")).toBeCloseTo(top, 0)
    expect(offset).toHaveBeenCalledTimes(1)
    resize()
    expect(offset).toHaveBeenCalledTimes(1)
  })
  it.each([0, 1, 2])("keeps passive growth separate at %ipx from the end", distance => {
    const h = mount()
    h.move(h.root.scrollHeight - scrollFixture.height - distance)
    const before = h.root.scrollTop
    const offset = vi.spyOn(scrollFixture.latest.virtualizer, "scrollToOffset")
    scrollFixture.bodyHeights.set("m13", 180)
    resize()
    expect(h.root.scrollTop - before).toBe(distance <= 1 ? 80 : 0)
    expect(offset).not.toHaveBeenCalled()
  })
  it("does not add a second prefix correction to a pinned single long row", () => {
    scrollFixture.bodyHeights.set("m0", 1800)
    const h = mount({ items: [message("m0")] })
    const before = h.root.scrollTop
    const offset = vi.spyOn(scrollFixture.latest.virtualizer, "scrollToOffset")
    scrollFixture.firstPrefix += 60
    h.update({ items: [...h.input.items] })
    expect(h.root.scrollTop - before).toBe(60)
    expect(offset).not.toHaveBeenCalled()
  })
  it.each([0, 99, 100, 101])("qualifies peer append from the actual prior %ipx tail distance", distance => {
    const h = mount()
    h.move(h.root.scrollHeight - scrollFixture.height - distance)
    const end = vi.spyOn(scrollFixture.latest.virtualizer, "scrollToEnd")
    h.update({ items: [...h.input.items, message("peer-new")] })
    expect(end).toHaveBeenCalledTimes(distance <= 100 ? 1 : 0)
  })
  it("does not follow a historical self-authored tail from newer pagination", () => {
    const h = mount({ viewerUserId: "me" })
    h.move(300)
    const end = vi.spyOn(scrollFixture.latest.virtualizer, "scrollToEnd")
    act(() => scrollFixture.latest.captureNewerPageAnchor())
    h.update({ isFetchingNewer: true })
    h.update({ items: [...h.input.items, message("historical-me", "me")], isFetchingNewer: false })
    h.update({ items: [...h.input.items] })
    expect(end).not.toHaveBeenCalled()
  })
  it("does not revive a canceled Present when its tail arrives late", () => {
    const h = mount({ hasMoreNewer: true, newDividerBefore: "m4", items: Array.from({ length: 14 }, (_, i) => ({ ...message(`m${i}`), newDivider: i === 4 })) })
    act(() => scrollFixture.latest.requestPresentPosition())
    h.move(300)
    const end = vi.spyOn(scrollFixture.latest.virtualizer, "scrollToEnd")
    h.update({ items: [...h.input.items, message("historical-me", "me")], hasMoreNewer: false, presentVersion: 1, viewerUserId: "me" })
    h.update({ items: [...h.input.items] })
    expect(end).not.toHaveBeenCalled()
  })
  it("finishes only the active Present ticket when the current tail arrives", () => {
    const h = mount({ hasMoreNewer: true, newDividerBefore: "m4", items: Array.from({ length: 14 }, (_, i) => ({ ...message(`m${i}`), newDivider: i === 4 })) })
    const end = vi.spyOn(scrollFixture.latest.virtualizer, "scrollToEnd")
    act(() => scrollFixture.latest.requestPresentPosition())
    expect(scrollFixture.latest.readPositionReady).toBe(false)
    h.update({ items: [...h.input.items, message("present-tail")], hasMoreNewer: false, presentVersion: 1 })
    expect(end).toHaveBeenCalledOnce()
    expect(h.root.scrollTop).toBe(h.root.scrollHeight - scrollFixture.height)
    expect(scrollFixture.latest.readPositionReady).toBe(true)
    h.update({ items: [...h.input.items] })
    expect(end).toHaveBeenCalledOnce()
  })
  it("waits for a positive viewport before proving the original semantic position", () => {
    scrollFixture.height = 0
    const h = mount({ newDividerBefore: "m4", items: Array.from({ length: 14 }, (_, i) => ({ ...message(`m${i}`), newDivider: i === 4 })) })
    expect(scrollFixture.latest.readPositionReady).toBe(false)
    scrollFixture.height = 500
    resize()
    expect(scrollFixture.latest.readPositionReady).toBe(true)
    act(() => scrollFixture.latest.jumpTo("m8", "auto"))
    scrollFixture.height = 0
    resize()
    expect(scrollFixture.latest.readPositionReady).toBe(false)
    scrollFixture.height = 500
    resize()
    expect(scrollFixture.latest.readPositionReady).toBe(true)
  })
  it("does not settle prefix or footer candidates while a pointer or moving touch is active", () => {
    scrollFixture.bodyHeights.set("m0", 1800)
    const h = mount()
    h.move(400)
    const offset = vi.spyOn(scrollFixture.latest.virtualizer, "scrollToOffset")
    fireEvent.pointerDown(h.root, { pointerId: 9 })
    scrollFixture.firstPrefix += 40
    h.update({ items: [...h.input.items] })
    expect(offset).not.toHaveBeenCalled()
    fireEvent.pointerUp(document, { pointerId: 9 })
    runFrames()
    fireEvent.touchStart(h.root, { touches: [{ clientY: 200 }] })
    fireEvent.touchMove(h.root, { touches: [{ clientY: 180 }] })
    scrollFixture.height -= 100
    resize()
    expect(offset).not.toHaveBeenCalled()
    fireEvent.blur(window)
    runFrames()
    expect(scrollFixture.latest.readPositionReady).toBe(true)
    expect(offset).not.toHaveBeenCalled()
  })
  it.each([0, 2, 100, 300])("retains the existing footer policy at %ipx and consumes duplicate delivery", distance => {
    const h = mount()
    h.move(h.root.scrollHeight - scrollFixture.height - distance)
    const before = h.root.scrollTop
    const offset = vi.spyOn(scrollFixture.latest.virtualizer, "scrollToOffset")
    scrollFixture.height -= 100
    resize()
    expect(h.root.scrollTop).toBe(before + (distance <= 100 ? 100 : 0))
    const calls = offset.mock.calls.length
    resize()
    expect(offset).toHaveBeenCalledTimes(calls)
  })
  it.each([0, 2, 100, 300])("preserves the footer policy at %ipx when viewport growth changes the folded row", distance => {
    const h = mount()
    h.move(h.root.scrollHeight - scrollFixture.height - distance)
    const before = h.root.scrollTop
    scrollFixture.height += 200
    resize()
    expect(h.root.scrollTop).toBe(before - (distance <= 100 ? 200 : 0))
    if (distance <= 100) expect(h.root.scrollHeight - scrollFixture.height - h.root.scrollTop).toBe(distance)
  })
  it("preserves a current two-pixel tail distance when the footer grows before the scroll quiet period", () => {
    const h = mount()
    act(() => h.root.scrollTo({ top: h.root.scrollHeight - scrollFixture.height - 2 }))
    runFrames(2)
    scrollFixture.height += 200
    resize()
    expect(h.root.scrollHeight - scrollFixture.height - h.root.scrollTop).toBe(2)
  })
  it.each([0, 2, 100, 101])("preserves the footer policy at %ipx across native mobile/desktop tail padding", distance => {
    const h = mount({ tailPaddingEnd: 40 })
    h.move(h.root.scrollHeight - scrollFixture.height - distance)
    const before = h.root.scrollTop
    const offset = vi.spyOn(scrollFixture.latest.virtualizer, "scrollToOffset")
    h.update({ tailPaddingEnd: 48 })
    expect(h.root.scrollTop).toBe(before + (distance <= 100 ? 8 : 0))
    const calls = offset.mock.calls.length
    h.update({ items: [...h.input.items] })
    expect(offset).toHaveBeenCalledTimes(calls)
    if (distance === 0) {
      scrollFixture.bodyHeights.set("m13", 240)
      h.update({ items: [...h.input.items] })
      expect(h.root.scrollTop).toBe(h.root.scrollHeight - scrollFixture.height)
      expect(offset).toHaveBeenCalledTimes(calls)
    }
  })
  it("preserves a two-pixel DM tail distance through consecutive composer resizes", () => {
    const h = mount()
    scrollFixture.height -= 100
    resize(2)
    act(() => h.root.scrollTo({ top: h.root.scrollHeight - scrollFixture.height - 2 }))
    runFrames(2)
    scrollFixture.height += 100
    resize()
    expect(h.root.scrollHeight - h.root.clientHeight - h.root.scrollTop).toBe(2)
  })
  it.each([0, 2, 8, 100, 300])("preserves the %ipx footer policy in the first two resize frames", distance => {
    const h = mount()
    h.move(h.root.scrollHeight - scrollFixture.height - distance)
    const before = h.root.scrollTop
    scrollFixture.height += 200
    resize(2)
    if (distance <= 100) expect(h.root.scrollHeight - h.root.clientHeight - h.root.scrollTop).toBe(distance)
    else expect(h.root.scrollTop).toBe(before)
  })
  it.each([[40, 48], [48, 40]])("retains an explicit present scroll after padding changes from %i to %i", (from, to) => {
    const h = mount({ tailPaddingEnd: from })
    h.move(300)
    h.stage({ tailPaddingEnd: to })
    act(() => h.root.scrollTo({ top: h.root.scrollHeight }))
    resize()
    expect(h.root.scrollHeight - h.root.clientHeight - h.root.scrollTop).toBe(0)
    expect(scrollFixture.latest.belowCount).toBe(0)
  })
  it.each(["wheel", "touch", "pointer"])("keeps footer clamp compensation behind active %s input", input => {
    const h = mount()
    h.move(h.root.scrollHeight - scrollFixture.height - 2)
    const offset = vi.spyOn(scrollFixture.latest.virtualizer, "scrollToOffset")
    if (input === "wheel") fireEvent.wheel(h.root, { deltaY: -2 })
    if (input === "touch") fireEvent.touchStart(h.root, { touches: [{ clientY: 200 }] })
    if (input === "pointer") fireEvent.pointerDown(h.root, { pointerId: 9 })
    scrollFixture.height += 100
    resize(2)
    expect(offset).not.toHaveBeenCalled()
  })
  it("does not treat a resize clamp during ongoing native scrolling as a settled footer", () => {
    const h = mount()
    h.move(h.root.scrollHeight - scrollFixture.height - 8)
    act(() => h.root.scrollTo({ top: h.root.scrollTop + 6 }))
    runFrames(2)
    expect(scrollFixture.latest.virtualizer.isScrolling).toBe(true)
    const offset = vi.spyOn(scrollFixture.latest.virtualizer, "scrollToOffset")
    scrollFixture.height += 100
    resize(2)
    expect(offset).not.toHaveBeenCalled()
  })
  it.each(["document", "footer"])("keeps a settled viewport anchor after an unregistered %s pointer release", target => {
    const h = mount()
    h.move(h.root.scrollHeight - scrollFixture.height - 2)
    const footer = h.root.closest('[data-slot="community-conversation-surface"]')!
      .querySelector('[data-slot="community-conversation-footer"]')!
    const release = new Event("pointerup", { bubbles: true })
    Object.defineProperty(release, "pointerId", { value: 41 })
    fireEvent(target === "document" ? document : footer, release)
    scrollFixture.height += 100
    resize(2)
    expect(h.root.scrollHeight - h.root.clientHeight - h.root.scrollTop).toBe(2)
  })
  it("keeps a real scroller pointer protected when released outside the scroller", () => {
    const h = mount()
    h.move(h.root.scrollHeight - scrollFixture.height - 2)
    const offset = vi.spyOn(scrollFixture.latest.virtualizer, "scrollToOffset")
    const down = new Event("pointerdown", { bubbles: true })
    Object.defineProperty(down, "pointerId", { value: 41 })
    fireEvent(h.root, down)
    const up = new Event("pointerup", { bubbles: true })
    Object.defineProperty(up, "pointerId", { value: 41 })
    fireEvent(document, up)
    scrollFixture.height += 100
    resize(2)
    expect(offset).not.toHaveBeenCalled()
  })
  it("does not release an active scroller pointer when another pointer ends outside", () => {
    const h = mount()
    h.move(h.root.scrollHeight - scrollFixture.height - 2)
    const offset = vi.spyOn(scrollFixture.latest.virtualizer, "scrollToOffset")
    const down = new Event("pointerdown", { bubbles: true })
    Object.defineProperty(down, "pointerId", { value: 41 })
    fireEvent(h.root, down)
    const up = new Event("pointerup", { bubbles: true })
    Object.defineProperty(up, "pointerId", { value: 42 })
    fireEvent(document, up)
    runFrames(13)
    scrollFixture.height += 100
    resize(2)
    expect(offset).not.toHaveBeenCalled()
  })
  it.each([0, 1])("preserves a settled viewport tail distance after ResizeObserver and %i later RAFs", frames => {
    const h = mount()
    h.move(h.root.scrollHeight - scrollFixture.height - 2)
    scrollFixture.height += 100
    act(() => {
      h.root.scrollTop = h.root.scrollHeight - h.root.clientHeight
      h.root.dispatchEvent(new Event("scroll"))
    })
    resize(0)
    runFrames(frames)
    expect(h.root.scrollHeight - h.root.clientHeight - h.root.scrollTop).toBe(2)
  })
  it.each([0, 2, 8, 100, 300])("preserves the %ipx footer policy in the first RAF before native ResizeObserver", distance => {
    const h = mount()
    h.move(h.root.scrollHeight - scrollFixture.height - distance)
    const before = h.root.scrollTop
    scrollFixture.height += 200
    runFrames(1)
    expect(h.root.scrollTop).toBe(before - (distance <= 100 ? 200 : 0))
    resize(0)
    expect(h.root.scrollTop).toBe(before - (distance <= 100 ? 200 : 0))
  })
  it("retains a settled viewport owner through successive first-RAF composer clamps", () => {
    const h = mount()
    h.move(h.root.scrollHeight - scrollFixture.height - 2)
    for (let i = 0; i < 3; i++) {
      scrollFixture.height += 50
      runFrames(1)
      expect(h.root.scrollHeight - h.root.clientHeight - h.root.scrollTop).toBe(2)
      resize(0)
      expect(h.root.scrollHeight - h.root.clientHeight - h.root.scrollTop).toBe(2)
      runFrames(1)
      expect(h.root.scrollHeight - h.root.clientHeight - h.root.scrollTop).toBe(2)
    }
  })
  it("keeps a registered pointer cancellation protected outside the scroller", () => {
    const h = mount()
    h.move(h.root.scrollHeight - scrollFixture.height - 2)
    const offset = vi.spyOn(scrollFixture.latest.virtualizer, "scrollToOffset")
    const down = new Event("pointerdown", { bubbles: true })
    Object.defineProperty(down, "pointerId", { value: 41 })
    fireEvent(h.root, down)
    const cancel = new Event("pointercancel", { bubbles: true })
    Object.defineProperty(cancel, "pointerId", { value: 41 })
    fireEvent(document, cancel)
    scrollFixture.height += 100
    resize(2)
    expect(offset).not.toHaveBeenCalled()
  })
  it("retires a held scroller pointer after window blur and the input quiet window", () => {
    const h = mount()
    h.move(h.root.scrollHeight - scrollFixture.height - 2)
    const down = new Event("pointerdown", { bubbles: true })
    Object.defineProperty(down, "pointerId", { value: 41 })
    fireEvent(h.root, down)
    fireEvent(window, new Event("blur"))
    runFrames(13)
    scrollFixture.height += 100
    resize(2)
    expect(h.root.scrollHeight - h.root.clientHeight - h.root.scrollTop).toBe(2)
  })
  it("rejects an unrelated native rectangle during a first-RAF viewport handoff", () => {
    const h = mount()
    h.move(h.root.scrollHeight - scrollFixture.height - 2)
    const offset = vi.spyOn(scrollFixture.latest.virtualizer, "scrollToOffset")
    scrollFixture.latest.virtualizer.scrollRect = { width: 320, height: 300 }
    scrollFixture.height += 100
    runFrames(1)
    expect(offset).not.toHaveBeenCalled()
  })
  it("fills a true single short message through native padding and crosses short/long normally", () => {
    const h = mount({ items: [message("m0")] })
    expect(h.root.scrollTop).toBe(0)
    expect(scrollFixture.latest.virtualizer.getTotalSize()).toBe(scrollFixture.height)
    h.update({ items: Array.from({ length: 14 }, (_, i) => message(`m${i}`)) })
    expect(scrollFixture.latest.virtualizer.getTotalSize()).toBeGreaterThan(scrollFixture.height)
    h.update({ items: [message("m0")] })
    expect(scrollFixture.latest.virtualizer.getTotalSize()).toBe(scrollFixture.height)
    expect(scrollFixture.latest.virtualizer.options.paddingStart).toBeGreaterThan(0)
  })
  it("keeps a genuinely empty list free of message keys and positions the first actual message", () => {
    const h = mount({ items: [] })
    expect(scrollFixture.latest.virtualizer.getVirtualItems()).toEqual([])
    expect(h.root.querySelector('[data-msg-id]')).toBeNull()
    h.update({ items: [message("first")] })
    expect(scrollFixture.latest.readPositionReady).toBe(true)
    expect(scrollFixture.latest.virtualizer.getVirtualItems().map(item => item.key)).toEqual(["msg:first"])
    expect(h.root.scrollTop).toBe(0)
    expect(scrollFixture.latest.virtualizer.getTotalSize()).toBe(scrollFixture.height)
  })
  it("stops idle geometry frames when the last message is removed", () => {
    const h = mount()
    h.update({ items: [] })
    runFrames()
    const frames = vi.mocked(window.requestAnimationFrame)
    frames.mockClear()
    runFrames(5)
    expect(frames).not.toHaveBeenCalled()
  })
  it("follows a new self-send once and retains its stable display key on canonical acknowledgement", () => {
    const h = mount({ viewerUserId: "me" })
    h.move(300)
    const end = vi.spyOn(scrollFixture.latest.virtualizer, "scrollToEnd")
    const optimistic = { ...message("optimistic", "me"), key: "client:send-1" }
    h.update({ items: [...h.input.items, optimistic] })
    expect(end).toHaveBeenCalledOnce()
    const canonical = { ...optimistic, m: { ...optimistic.m, id: "canonical" } }
    h.update({ items: [...h.input.items.slice(0, -1), canonical] })
    expect(end).toHaveBeenCalledOnce()
    expect(scrollFixture.latest.virtualizer.getVirtualItems().at(-1)?.key).toBe("client:send-1")
  })
  it("keeps read closed at the early warm tail until the original unread boundary is proven", () => {
    const h = mount({ initialScrollReady: false })
    expect(scrollFixture.latest.readPositionReady).toBe(false)
    expect(h.root.scrollTop).toBe(h.root.scrollHeight - scrollFixture.height)
    h.update({ initialScrollReady: true, newDividerBefore: "m4", items: h.input.items.map(item => ({ ...item, newDivider: item.m.id === "m4" })) })
    const marker = h.root.querySelector('[data-new-divider]')!.getBoundingClientRect()
    expect((marker.top + marker.bottom) / 2).toBeCloseTo(scrollFixture.height / 2, 0)
    expect(scrollFixture.latest.readPositionReady).toBe(true)
  })
  it("combines current prefix growth with the existing footer reading-offset policy once", () => {
    scrollFixture.bodyHeights.set("m0", 1800)
    const h = mount()
    h.move(400)
    const before = bodyTop(h.root, "m0")
    const offset = vi.spyOn(scrollFixture.latest.virtualizer, "scrollToOffset")
    scrollFixture.height -= 100
    scrollFixture.firstPrefix += 40
    h.update({ items: [...h.input.items] })
    expect(bodyTop(h.root, "m0")).toBeCloseTo(before, 0)
    expect(offset).toHaveBeenCalledOnce()
    resize()
    expect(offset).toHaveBeenCalledOnce()
  })
})
