import { beforeEach, afterEach, describe, expect, it, vi } from "vitest"
import { act, fireEvent } from "@/test/react-dom-harness"
import { bodyTop, installMessageScrollFixture, restoreMessageScrollFixture, message, mount, resize, runFrames, scrollFixture } from "@/test/message-scroll-fixture"

beforeEach(installMessageScrollFixture)
afterEach(restoreMessageScrollFixture)

describe("locked native adapter and existing message scroll owner", () => {
  it("unifies native total and DOM max while keeping 40/48px rail clearance", () => {
    const h = mount()
    expect(scrollFixture.latest.readPositionReady).toBe(true)
    expect(scrollFixture.latest.virtualizer.options).toMatchObject({ anchorTo: "end", followOnAppend: false, scrollEndThreshold: 1, scrollMargin: 0, paddingEnd: 48 })
    expect(h.root.scrollHeight).toBe(scrollFixture.latest.virtualizer.getTotalSize())
    expect(h.root.scrollTop).toBe(h.root.scrollHeight - scrollFixture.height)
    h.update({ tailPaddingEnd: 40 })
    expect(h.root.scrollHeight).toBe(scrollFixture.latest.virtualizer.getTotalSize())
  })
  it("centers the actual New prefix of a long message with one business correction", () => {
    scrollFixture.bodyHeights.set("m4", 1800)
    const items = Array.from({ length: 12 }, (_, i) => ({ ...message(`m${i}`), ...(i === 4 ? { newDivider: true } : {}) }))
    const h = mount({ items, newDividerBefore: "m4", hasMoreNewer: true })
    const marker = h.root.querySelector('[data-new-divider]')!.getBoundingClientRect()
    expect((marker.top + marker.bottom) / 2).toBeCloseTo(scrollFixture.height / 2, 0)
    expect(bodyTop(h.root, "m4")).toBeLessThan(scrollFixture.height)
    expect(scrollFixture.latest.readPositionReady).toBe(true)
  })
  it("clamps a first-row merged date/New boundary to the actual content origin", () => {
    scrollFixture.firstPrefix = 152
    scrollFixture.bodyHeights.set("first", 1800)
    const item = { ...message("first"), dateLabel: "Today", newDivider: true }
    const h = mount({ items: [item], hasMoreOlder: false, newDividerBefore: "first" })
    const marker = h.root.querySelector('[data-new-divider]')!.getBoundingClientRect()
    expect(h.root.scrollTop).toBe(0)
    expect(marker.top).toBeGreaterThanOrEqual(0)
    expect(marker.bottom).toBeLessThan(scrollFixture.height)
    expect(bodyTop(h.root, "first")).toBeLessThan(scrollFixture.height)
    expect(scrollFixture.latest.readPositionReady).toBe(true)
  })
  it("shows after the original deadline while keeping read and peer follow closed", () => {
    const shown = vi.fn()
    const h = mount({ initialScrollReady: false, hasMoreNewer: true, onInitialPositionSettled: shown })
    act(() => vi.advanceTimersByTime(2000))
    runFrames()
    expect(shown).toHaveBeenCalledOnce()
    expect(scrollFixture.latest.readPositionReady).toBe(false)
    expect(scrollFixture.latest.virtualizer.options.anchorTo).toBe("start")
    const before = h.root.scrollTop
    h.update({ items: [...h.input.items, message("late-peer")] })
    expect(h.root.scrollTop).toBe(before)
    expect(scrollFixture.latest.readPositionReady).toBe(false)
    h.move(300)
    expect(scrollFixture.latest.readPositionReady).toBe(true)
  })
  it("does not let pagination retire an unresolved initial intent or its deadline", () => {
    const shown = vi.fn()
    const h = mount({ initialScrollReady: false, hasMoreNewer: true, onInitialPositionSettled: shown })
    act(() => scrollFixture.latest.captureOlderPageAnchor())
    h.update({ isFetchingOlder: true })
    h.update({ isFetchingOlder: false })
    expect(scrollFixture.latest.virtualizer.options.anchorTo).toBe("start")
    act(() => vi.advanceTimersByTime(2000))
    expect(shown).toHaveBeenCalledOnce()
    expect(scrollFixture.latest.readPositionReady).toBe(false)
  })
  it("uses stable native keys for ordinary prepend without a business index restore", () => {
    const h = mount()
    h.move(500)
    const top = bodyTop(h.root, "m5")
    const index = vi.spyOn(scrollFixture.latest.virtualizer, "scrollToIndex")
    const offset = vi.spyOn(scrollFixture.latest.virtualizer, "scrollToOffset")
    act(() => scrollFixture.latest.captureOlderPageAnchor())
    h.update({ isFetchingOlder: true })
    h.update({ items: [message("older"), ...h.input.items], isFetchingOlder: false })
    expect(bodyTop(h.root, "m5")).toBeCloseTo(top, 0)
    expect(index).not.toHaveBeenCalled()
    expect(offset).not.toHaveBeenCalled()
    expect(scrollFixture.latest.isOlderPageAnchorSettling).toBe(false)
  })
  it("repairs only the current message prefix when an old first row loses its header", () => {
    scrollFixture.bodyHeights.set("m0", 1200)
    const h = mount()
    h.move(400)
    const top = bodyTop(h.root, "m0")
    const offset = vi.spyOn(scrollFixture.latest.virtualizer, "scrollToOffset")
    h.update({ items: [message("older"), ...h.input.items] })
    expect(bodyTop(h.root, "m0")).toBeCloseTo(top, 0)
    expect(offset).toHaveBeenCalledTimes(1)
  })
  it("does not duplicate native growth above the fold", () => {
    const h = mount()
    h.move(500)
    const top = bodyTop(h.root, "m5")
    const offset = vi.spyOn(scrollFixture.latest.virtualizer, "scrollToOffset")
    scrollFixture.bodyHeights.set("m0", 220)
    resize()
    expect(bodyTop(h.root, "m5")).toBeCloseTo(top, 0)
    expect(offset).not.toHaveBeenCalled()
  })
  it("settles same-anchor hero growth once after native layout", () => {
    scrollFixture.bodyHeights.set("m0", 1200)
    const h = mount()
    h.move(400)
    const top = bodyTop(h.root, "m0")
    const offset = vi.spyOn(scrollFixture.latest.virtualizer, "scrollToOffset")
    scrollFixture.firstPrefix += 40
    h.update({ items: [...h.input.items] })
    expect(bodyTop(h.root, "m0")).toBeCloseTo(top, 0)
    expect(offset).toHaveBeenCalledTimes(1)
    resize()
    expect(offset).toHaveBeenCalledTimes(1)
  })
  it.each([0, 1, 2])("keeps passive growth separate at %ipx from the end", distance => {
    const h = mount()
    h.move(h.root.scrollHeight - scrollFixture.height - distance)
    const before = h.root.scrollTop
    const offset = vi.spyOn(scrollFixture.latest.virtualizer, "scrollToOffset")
    scrollFixture.bodyHeights.set("m13", 180)
    resize()
    expect(h.root.scrollTop - before).toBe(distance <= 1 ? 80 : 0)
    expect(offset).not.toHaveBeenCalled()
  })
  it("does not add a second prefix correction to a pinned single long row", () => {
    scrollFixture.bodyHeights.set("m0", 1800)
    const h = mount({ items: [message("m0")] })
    const before = h.root.scrollTop
    const offset = vi.spyOn(scrollFixture.latest.virtualizer, "scrollToOffset")
    scrollFixture.firstPrefix += 60
    h.update({ items: [...h.input.items] })
    expect(h.root.scrollTop - before).toBe(60)
    expect(offset).not.toHaveBeenCalled()
  })
  it.each([0, 99, 100, 101])("qualifies peer append from the actual prior %ipx tail distance", distance => {
    const h = mount()
    h.move(h.root.scrollHeight - scrollFixture.height - distance)
    const end = vi.spyOn(scrollFixture.latest.virtualizer, "scrollToEnd")
    h.update({ items: [...h.input.items, message("peer-new")] })
    expect(end).toHaveBeenCalledTimes(distance <= 100 ? 1 : 0)
  })
  it("does not follow a historical self-authored tail from newer pagination", () => {
    const h = mount({ viewerUserId: "me" })
    h.move(300)
    const end = vi.spyOn(scrollFixture.latest.virtualizer, "scrollToEnd")
    act(() => scrollFixture.latest.captureNewerPageAnchor())
    h.update({ isFetchingNewer: true })
    h.update({ items: [...h.input.items, message("historical-me", "me")], isFetchingNewer: false })
    h.update({ items: [...h.input.items] })
    expect(end).not.toHaveBeenCalled()
  })
  it("does not revive a canceled Present when its tail arrives late", () => {
    const h = mount({ hasMoreNewer: true, newDividerBefore: "m4", items: Array.from({ length: 14 }, (_, i) => ({ ...message(`m${i}`), newDivider: i === 4 })) })
    act(() => scrollFixture.latest.requestPresentPosition())
    h.move(300)
    const end = vi.spyOn(scrollFixture.latest.virtualizer, "scrollToEnd")
    h.update({ items: [...h.input.items, message("historical-me", "me")], hasMoreNewer: false, presentVersion: 1, viewerUserId: "me" })
    h.update({ items: [...h.input.items] })
    expect(end).not.toHaveBeenCalled()
  })
  it("finishes only the active Present ticket when the current tail arrives", () => {
    const h = mount({ hasMoreNewer: true, newDividerBefore: "m4", items: Array.from({ length: 14 }, (_, i) => ({ ...message(`m${i}`), newDivider: i === 4 })) })
    const end = vi.spyOn(scrollFixture.latest.virtualizer, "scrollToEnd")
    act(() => scrollFixture.latest.requestPresentPosition())
    expect(scrollFixture.latest.readPositionReady).toBe(false)
    h.update({ items: [...h.input.items, message("present-tail")], hasMoreNewer: false, presentVersion: 1 })
    expect(end).toHaveBeenCalledOnce()
    expect(h.root.scrollTop).toBe(h.root.scrollHeight - scrollFixture.height)
    expect(scrollFixture.latest.readPositionReady).toBe(true)
    h.update({ items: [...h.input.items] })
    expect(end).toHaveBeenCalledOnce()
  })
  it("waits for a positive viewport before proving the original semantic position", () => {
    scrollFixture.height = 0
    const h = mount({ newDividerBefore: "m4", items: Array.from({ length: 14 }, (_, i) => ({ ...message(`m${i}`), newDivider: i === 4 })) })
    expect(scrollFixture.latest.readPositionReady).toBe(false)
    scrollFixture.height = 500
    resize()
    expect(scrollFixture.latest.readPositionReady).toBe(true)
    act(() => scrollFixture.latest.jumpTo("m8", "auto"))
    scrollFixture.height = 0
    resize()
    expect(scrollFixture.latest.readPositionReady).toBe(false)
    scrollFixture.height = 500
    resize()
    expect(scrollFixture.latest.readPositionReady).toBe(true)
  })
  it("does not settle prefix or footer candidates while a pointer or moving touch is active", () => {
    scrollFixture.bodyHeights.set("m0", 1800)
    const h = mount()
    h.move(400)
    const offset = vi.spyOn(scrollFixture.latest.virtualizer, "scrollToOffset")
    fireEvent.pointerDown(h.root, { pointerId: 9 })
    scrollFixture.firstPrefix += 40
    h.update({ items: [...h.input.items] })
    expect(offset).not.toHaveBeenCalled()
    fireEvent.pointerUp(document, { pointerId: 9 })
    runFrames()
    fireEvent.touchStart(h.root, { touches: [{ clientY: 200 }] })
    fireEvent.touchMove(h.root, { touches: [{ clientY: 180 }] })
    scrollFixture.height -= 100
    resize()
    expect(offset).not.toHaveBeenCalled()
    fireEvent.blur(window)
    runFrames()
    expect(scrollFixture.latest.readPositionReady).toBe(true)
    expect(offset).not.toHaveBeenCalled()
  })
  it.each([0, 2, 100, 300])("retains the existing footer policy at %ipx and consumes duplicate delivery", distance => {
    const h = mount()
    h.move(h.root.scrollHeight - scrollFixture.height - distance)
    const before = h.root.scrollTop
    const offset = vi.spyOn(scrollFixture.latest.virtualizer, "scrollToOffset")
    scrollFixture.height -= 100
    resize()
    expect(h.root.scrollTop).toBe(before + (distance <= 100 ? 100 : 0))
    const calls = offset.mock.calls.length
    resize()
    expect(offset).toHaveBeenCalledTimes(calls)
  })
  it("fills a true single short message through native padding and crosses short/long normally", () => {
    const h = mount({ items: [message("m0")] })
    expect(h.root.scrollTop).toBe(0)
    expect(scrollFixture.latest.virtualizer.getTotalSize()).toBe(scrollFixture.height)
    h.update({ items: Array.from({ length: 14 }, (_, i) => message(`m${i}`)) })
    expect(scrollFixture.latest.virtualizer.getTotalSize()).toBeGreaterThan(scrollFixture.height)
    h.update({ items: [message("m0")] })
    expect(scrollFixture.latest.virtualizer.getTotalSize()).toBe(scrollFixture.height)
    expect(scrollFixture.latest.virtualizer.options.paddingStart).toBeGreaterThan(0)
  })
  it("keeps a genuinely empty list free of message keys and positions the first actual message", () => {
    const h = mount({ items: [] })
    expect(scrollFixture.latest.virtualizer.getVirtualItems()).toEqual([])
    expect(h.root.querySelector('[data-msg-id]')).toBeNull()
    h.update({ items: [message("first")] })
    expect(scrollFixture.latest.readPositionReady).toBe(true)
    expect(scrollFixture.latest.virtualizer.getVirtualItems().map(item => item.key)).toEqual(["msg:first"])
    expect(h.root.scrollTop).toBe(0)
    expect(scrollFixture.latest.virtualizer.getTotalSize()).toBe(scrollFixture.height)
  })
  it("follows a new self-send once and retains its stable display key on canonical acknowledgement", () => {
    const h = mount({ viewerUserId: "me" })
    h.move(300)
    const end = vi.spyOn(scrollFixture.latest.virtualizer, "scrollToEnd")
    const optimistic = { ...message("optimistic", "me"), key: "client:send-1" }
    h.update({ items: [...h.input.items, optimistic] })
    expect(end).toHaveBeenCalledOnce()
    const canonical = { ...optimistic, m: { ...optimistic.m, id: "canonical" } }
    h.update({ items: [...h.input.items.slice(0, -1), canonical] })
    expect(end).toHaveBeenCalledOnce()
    expect(scrollFixture.latest.virtualizer.getVirtualItems().at(-1)?.key).toBe("client:send-1")
  })
  it("keeps read closed at the early warm tail until the original unread boundary is proven", () => {
    const h = mount({ initialScrollReady: false })
    expect(scrollFixture.latest.readPositionReady).toBe(false)
    expect(h.root.scrollTop).toBe(h.root.scrollHeight - scrollFixture.height)
    h.update({ initialScrollReady: true, newDividerBefore: "m4", items: h.input.items.map(item => ({ ...item, newDivider: item.m.id === "m4" })) })
    const marker = h.root.querySelector('[data-new-divider]')!.getBoundingClientRect()
    expect((marker.top + marker.bottom) / 2).toBeCloseTo(scrollFixture.height / 2, 0)
    expect(scrollFixture.latest.readPositionReady).toBe(true)
  })
  it("combines current prefix growth with the existing footer reading-offset policy once", () => {
    scrollFixture.bodyHeights.set("m0", 1800)
    const h = mount()
    h.move(400)
    const before = bodyTop(h.root, "m0")
    const offset = vi.spyOn(scrollFixture.latest.virtualizer, "scrollToOffset")
    scrollFixture.height -= 100
    scrollFixture.firstPrefix += 40
    h.update({ items: [...h.input.items] })
    expect(bodyTop(h.root, "m0")).toBeCloseTo(before, 0)
    expect(offset).toHaveBeenCalledOnce()
    resize()
    expect(offset).toHaveBeenCalledOnce()
  })
})
