import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { resolve } from "node:path"
import { afterEach, describe, expect, it } from "vitest"
import { stageServiceWorker } from "./stage-service-worker"

const temporaryRoots: string[] = []
afterEach(() => {
  for (const root of temporaryRoots.splice(0)) rmSync(root, { recursive: true, force: true })
})

function fixture() {
  const root = mkdtempSync(resolve(tmpdir(), "alook-stage-sw-"))
  temporaryRoots.push(root)
  mkdirSync(resolve(root, ".next/server/app/serwist"), { recursive: true })
  mkdirSync(resolve(root, "public"))
  const meta = { status: 200, headers: { "content-type": "application/javascript", "service-worker-allowed": "/", "cache-control": "no-cache" } }
  writeFileSync(resolve(root, ".next/server/app/serwist/sw.js.meta"), JSON.stringify(meta))
  writeFileSync(resolve(root, ".next/server/app/serwist/sw.js.body"), "self.buildVersion='current';")
  writeFileSync(resolve(root, "public/sw.js"), "self.buildVersion='old';")
  return { root, meta }
}

describe("public SW static staging", () => {
  it("replaces the previous public script with the exact generated bytes", () => {
    const { root } = fixture()
    stageServiceWorker(root)
    expect(readFileSync(resolve(root, "public/sw.js"))).toEqual(readFileSync(resolve(root, ".next/server/app/serwist/sw.js.body")))
  })

  it.each(["status", "content-type", "service-worker-allowed", "cache-control"])("rejects invalid %s metadata without publishing it", field => {
    const { root, meta } = fixture()
    if (field === "status") meta.status = 500
    else meta.headers[field as keyof typeof meta.headers] = "invalid"
    writeFileSync(resolve(root, ".next/server/app/serwist/sw.js.meta"), JSON.stringify(meta))
    expect(() => stageServiceWorker(root)).toThrow("Generated public service worker metadata is invalid")
    expect(readFileSync(resolve(root, "public/sw.js"), "utf8")).toBe("self.buildVersion='old';")
  })

  it("fails rather than reusing a stale script when the current build is absent", () => {
    const { root } = fixture()
    rmSync(resolve(root, ".next/server/app/serwist/sw.js.body"))
    expect(() => stageServiceWorker(root)).toThrow()
  })
})
