// The import below is generated by `opennextjs-cloudflare build` and doesn't
// exist at typecheck time. The build step creates it before wrangler bundles.
// @ts-ignore — generated at build time, may not exist yet
import openNextHandler from "./.open-next/worker.js"
import { createWebWorkerHandler } from "./src/lib/worker-runtime"

// @ts-ignore — generated at build time, may not exist yet
export { DOQueueHandler } from "./.open-next/worker.js"

export default createWebWorkerHandler(openNextHandler as ExportedHandler<CloudflareEnv>)
