// The import below is generated by `opennextjs-cloudflare build` and doesn't
// exist at typecheck time. The build step creates it before wrangler bundles.
// @ts-ignore — generated at build time, may not exist yet
import openNextHandler from "./.open-next/worker.js"
import { createWebWorkerHandler } from "./src/lib/worker-runtime"
import type { NextConfig } from "next"
import { resolveObservationBuild } from "./src/lib/observability/build"
// @ts-ignore — generated by Next build before the Worker bundle
import requiredServerFiles from "./.open-next/server-functions/default/src/web/.next/required-server-files.json"

// @ts-ignore — generated at build time, may not exist yet
export { DOQueueHandler } from "./.open-next/worker.js"

const build = resolveObservationBuild((requiredServerFiles as { config: Pick<NextConfig, "env"> }).config.env ?? {})
export default createWebWorkerHandler(openNextHandler as ExportedHandler<CloudflareEnv>, build)
