// Single source of truth for community `data-testid` values. Imported by both
// product components (so the attribute strings are never hand-typed) and the
// Playwright specs (via _fixtures/testids). Naming: community-<区域>-<元素>[-<标识>].
export const tid = {
  composerInput: "community-composer-input",
  channelComposerShell: "community-composer-shell",
  composerFileInput: "community-composer-file-input",
  composerSend: "community-composer-send",
  composerAttach: "community-composer-attach",
  composerAccessoryRail: "community-composer-accessory-rail",
  scrollToPresent: "community-scroll-to-present",
  messageSelectionToolbar: "community-message-selection-toolbar",
  messageScroller: "community-message-scroller",
  wsStatus: "community-ws-status",
  wsRetry: "community-ws-retry",
  serverAdd: "community-server-add",
  serverRailScroll: "community-server-rail-scroll",
  channelSidebarScroll: "community-channel-sidebar-scroll",
  createServerSubmit: "community-create-server-submit",
  createServerName: "community-create-server-name",
  createChannelSubmit: "community-create-channel-submit",
  settingsShell: "community-settings-shell",
  settingsNav: "community-settings-nav",
  settingsContent: "community-settings-content",
  settingsClose: "community-settings-close",
  settingsLabel: "community-settings-label",
  settingsTab: (value: string) => `community-settings-tab-${value}`,
  userSettingsOpen: "community-user-settings-open",
  serverSettingsOpen: "community-server-settings-open",
  serverSettingsName: "community-server-settings-name",
  newDivider: "community-new-divider",
  typingIndicator: "community-typing-indicator",
  dmBlockedNotice: "community-dm-blocked-notice",
  profileCard: "community-profile-card",
  profileContextBadge: "community-profile-context-badge",
  profileBotBadge: "community-profile-bot-badge",
  profileOwnerLink: "community-profile-owner-link",
  botAuditPreview: "community-bot-audit-preview",
  botAuditPreviewDock: "community-bot-audit-preview-dock",
  botAuditPreviewActive: "community-bot-audit-preview-active",
  botActivityModal: "bot-activity-modal",
  botAuditPreviewRow: (id: string) => `community-bot-audit-preview-row-${id}`,
  statusPill: "community-status-pill",
  inviteToken: "community-invite-token",
  inviteCopy: "community-invite-copy",
  inviteCard: (token: string) => `community-invite-card-${token}`,
  inviteCardAction: (token: string) => `community-invite-card-action-${token}`,
  machinePairOpen: "community-machine-pair-open",
  machinePairCommand: "community-machine-pair-command",
  machinePairCopy: "community-machine-pair-copy",
  machinePairDesktopConnect: "community-machine-pair-desktop-connect",
  machinePairRuntimeHint: "community-machine-pair-runtime-hint",
  machinePairStatus: "community-machine-pair-status",
  machineActions: (id: string) => `machine-actions-${id}`,
  machineUpdate: (id: string) => `machine-update-${id}`,
  machineUpdateConfirm: "machine-update-confirm",
  homeButton: "community-home-button",
  alookLogo: "community-alook-logo",
  botReportProblemItem: "bot-report-problem-item",
  botReportProblemDialog: "bot-report-problem-dialog",
  botReportProblemSubmit: "bot-report-problem-submit",
  botReportProblemStatus: "bot-report-problem-status",
  botAvatarPickerTrigger: "community-bot-avatar-picker-trigger",

  forumTagDialog: "community-forum-tag-dialog",
  forumTagDialogChip: (tag: string) => `community-forum-tag-dialog-chip-${tag}`,
  imageLightbox: "community-image-lightbox",
  imageLightboxThumbnail: "community-image-lightbox-thumbnail",
  imageLightboxOriginal: "community-image-lightbox-original",
  imageLightboxLoading: "community-image-lightbox-loading",
  imageLightboxError: "community-image-lightbox-error",
  imageLightboxRetry: "community-image-lightbox-retry",
  linkPreviewCard: "community-link-preview-card",
  linkPreviewThumbnail: "community-link-preview-thumbnail",

  message: (id: string) => `community-message-${id}`,
  messageImage: (id: string, index: number) => `community-message-image-${id}-${index}`,
  threadOpenerImage: (index: number) => `community-thread-opener-image-${index}`,
  attachmentCard: (name: string) => `community-attachment-card-${name}`,
  attachmentPreviewSheet: "community-attachment-preview-sheet",
  attachmentPreviewDownload: "community-attachment-preview-download",
  attachmentPreviewContent: "community-attachment-preview-content",
  mediaBlock: (name: string) => `community-media-block-${name}`,
  mediaPlay: (name: string) => `community-media-play-${name}`,
  mediaPlayer: (name: string) => `community-media-player-${name}`,
  mediaCollapse: (name: string) => `community-media-collapse-${name}`,
  mediaDownload: (name: string) => `community-media-download-${name}`,
  mediaRetry: (name: string) => `community-media-retry-${name}`,
  mediaStatus: (name: string) => `community-media-status-${name}`,
  codePreview: "community-code-preview",
  codePreviewLanguage: "community-code-preview-language",
  codePreviewCopy: "community-code-preview-copy",
  codePreviewWrap: "community-code-preview-wrap",
  codePreviewStatus: "community-code-preview-status",
  channelRow: (id: string) => `community-channel-row-${id}`,
  serverIcon: (id: string) => `community-server-icon-${id}`,
  dmRow: (id: string) => `community-dm-row-${id}`,
  memberRow: (id: string) => `community-member-row-${id}`,
  mentionOption: (id: string) => `community-mention-option-${id}`,
  mentionPopup: "community-mention-popup",
  mentionStatus: "community-mention-status",
  channelRefOption: (id: string) => `community-channel-ref-option-${id}`,
  reactionAdd: (msgId: string) => `community-reaction-add-${msgId}`,
  messageShare: (msgId: string) => `community-message-share-${msgId}`,
  messageShareCopy: `community-message-share-copy`,
  threadIndicator: (msgId: string) => `community-thread-indicator-${msgId}`,
  railUnreadBadge: (serverId: string) => `community-rail-unread-badge-${serverId}`,
  // Forum post feed (ForumView). `forumThreadCard` is the whole clickable card;
  // `forumThreadTitle` / `forumThreadTitleText` expose the clamped title cluster
  // and its visible text; `forumThreadTagBtn` is the responsive tag-edit icon;
  // `forumThreadDeleteBtn` is the responsive delete icon; `forumThreadAvatars`
  // wraps the participant AvatarGroup; `forumTagChip` is a filter-bar tag chip.
  forumThreadCard: (id: string) => `community-forum-post-${id}`,
  forumSidebarThread: (id: string) => `community-forum-sidebar-thread-${id}`,
  forumThreadTitle: (id: string) => `community-forum-post-title-${id}`,
  forumThreadTitleText: (id: string) => `community-forum-post-title-text-${id}`,
  forumThreadSeq: (id: string) => `community-forum-post-seq-${id}`,
  forumThreadTagBtn: (id: string) => `community-forum-post-tag-btn-${id}`,
  forumThreadDeleteBtn: (id: string) => `community-forum-post-delete-btn-${id}`,
  forumThreadAvatars: (id: string) => `community-forum-post-avatars-${id}`,
  forumFilterBar: "community-forum-filter-bar",
  forumTagScroller: "community-forum-tag-scroller",
  forumTagFadeLeft: "community-forum-tag-fade-left",
  forumTagFadeRight: "community-forum-tag-fade-right",
  forumTagAll: "community-forum-tag-all",
  forumTagChip: (tag: string) => `community-forum-tag-chip-${tag}`,
  forumNewPost: "community-forum-new-post",
  forumPostList: "community-forum-post-list",
  inboxUnreadChannel: (id: string) => `community-inbox-unread-channel-${id}`,
  inboxUnreadChild: (id: string) => `community-inbox-unread-child-${id}`,
  inboxUnreadDm: (id: string) => `community-inbox-unread-dm-${id}`,
  channelRefPill: (id: string) => `community-channel-ref-pill-${id}`,
} as const
