// Single source of truth for community `data-testid` values. Imported by both
// product components (so the attribute strings are never hand-typed) and the
// Playwright specs (via _fixtures/testids). Naming: community-<区域>-<元素>[-<标识>].
export const tid = {
  composerInput: "community-composer-input",
  channelComposerShell: "community-composer-shell",
  composerFileInput: "community-composer-file-input",
  composerSend: "community-composer-send",
  composerAttach: "community-composer-attach",
  composerAccessoryRail: "community-composer-accessory-rail",
  scrollToPresent: "community-scroll-to-present",
  messageSelectionToolbar: "community-message-selection-toolbar",
  messageScroller: "community-message-scroller",
  wsReconnectOverlay: "community-ws-reconnect-overlay",
  wsRetry: "community-ws-retry",
  initialFrame: "community-initial-frame",
  initialRailPending: "community-initial-rail-pending",
  initialUserBarPending: "community-initial-user-bar-pending",
  pendingMain: (kind: string) => `community-pending-main-${kind}`,
  serverAdd: "community-server-add",
  serverRailScroll: "community-server-rail-scroll",
  serverRailFolder: (id: string) => `community-server-folder-${id}`,
  serverRailIndicator: (id: string) => `community-server-rail-indicator-${id}`,
  serverRailFolderIndicator: (id: string) => `community-server-rail-folder-indicator-${id}`,
  serverRailInsert: (id: string) => `community-server-rail-insert-${id}`,
  serverRailInsertFolder: (id: string) => `community-server-rail-insert-folder-${id}`,
  channelSidebarScroll: "community-channel-sidebar-scroll",
  channelSidebarPending: (serverId: string) => `community-channel-sidebar-pending-${serverId}`,
  channelHeaderServer: (serverId: string) => `community-channel-header-server-${serverId}`,
  channelHeaderParent: (channelId: string) => `community-channel-header-parent-${channelId}`,
  channelHeaderServerLoading: "community-channel-header-server-loading",
  dmSidebarPending: "community-dm-sidebar-pending",
  createServerSubmit: "community-create-server-submit",
  createServerName: "community-create-server-name",
  createChannelSubmit: "community-create-channel-submit",
  settingsShell: "community-settings-shell",
  settingsNav: "community-settings-nav",
  settingsContent: "community-settings-content",
  settingsClose: "community-settings-close",
  settingsLabel: "community-settings-label",
  settingsTab: (value: string) => `community-settings-tab-${value}`,
  userSettingsOpen: "community-user-settings-open",
  serverSettingsOpen: "community-server-settings-open",
  serverSettingsName: "community-server-settings-name",
  newDivider: "community-new-divider",
  typingIndicator: "community-typing-indicator",
  dmBlockedNotice: "community-dm-blocked-notice",
  dmHeader: "community-dm-header",
  dmHeaderTitle: "community-dm-header-title",
  profileCard: "community-profile-card",
  profileContextBadge: "community-profile-context-badge",
  profileBotBadge: "community-profile-bot-badge",
  profileOwnerLink: "community-profile-owner-link",
  botAuditPreview: "community-bot-audit-preview",
  botAuditPreviewDock: "community-bot-audit-preview-dock",
  botAuditPreviewActive: "community-bot-audit-preview-active",
  botActivityModal: "bot-activity-modal",
  botAuditPreviewRow: (id: string) => `community-bot-audit-preview-row-${id}`,
  statusPill: "community-status-pill",
  inviteToken: "community-invite-token",
  inviteCopy: "community-invite-copy",
  inviteCard: (token: string) => `community-invite-card-${token}`,
  inviteCardAction: (token: string) => `community-invite-card-action-${token}`,
  machinePairOpen: "community-machine-pair-open",
  machineGuideIntroSource: "machine-guide-intro-source",
  machineFirstSignupGuide: "machine-first-signup-guide",
  machineGuideAvatarTarget: "machine-guide-avatar-target",
  machinePairCommand: "community-machine-pair-command",
  machinePairCopy: "community-machine-pair-copy",
  machinePairDesktopConnect: "community-machine-pair-desktop-connect",
  machinePairRuntimeHint: "community-machine-pair-runtime-hint",
  machinePairStatus: "community-machine-pair-status",
  machineActions: (id: string) => `machine-actions-${id}`,
  machineUpdate: (id: string) => `machine-update-${id}`,
  machineUpdateConfirm: "machine-update-confirm",
  daemonUpdateNotice: "daemon-update-notice",
  daemonUpdateAction: "daemon-update-action",
  homeButton: "community-home-button",
  alookLogo: "community-alook-logo",
  botReportProblemItem: "bot-report-problem-item",
  botReportProblemDialog: "bot-report-problem-dialog",
  botReportProblemSubmit: "bot-report-problem-submit",
  botReportProblemStatus: "bot-report-problem-status",
  botAvatarPickerTrigger: "community-bot-avatar-picker-trigger",
  botReasoningEffort: "community-bot-reasoning-effort",
  botCardModel: "bot-card-model",
  botUsage: (botId: string) => `community-bot-usage-${botId}`,
  botUsageDay: (botId: string, day: string) => `community-bot-usage-day-${botId}-${day}`,
  machineQuota: (machineId: string) => `community-machine-quota-${machineId}`,
  machineQuotaDetail: (machineId: string) => `community-machine-quota-detail-${machineId}`,

  forumTagDialog: "community-forum-tag-dialog",
  forumTagDialogBody: "community-forum-tag-dialog-body",
  forumTagDialogInput: "community-forum-tag-dialog-input",
  forumTagDialogCancel: "community-forum-tag-dialog-cancel",
  forumTagDialogSave: "community-forum-tag-dialog-save",
  forumTagDialogChip: (tag: string) => `community-forum-tag-dialog-chip-${tag}`,
  imageLightbox: "community-image-lightbox",
  imageLightboxThumbnail: "community-image-lightbox-thumbnail",
  imageLightboxOriginal: "community-image-lightbox-original",
  imageLightboxLoading: "community-image-lightbox-loading",
  imageLightboxError: "community-image-lightbox-error",
  imageLightboxRetry: "community-image-lightbox-retry",

  message: (id: string) => `community-message-${id}`,
  messageImage: (id: string, index: number) => `community-message-image-${id}-${index}`,
  threadOpenerImage: (index: number) => `community-thread-opener-image-${index}`,
  attachmentCard: (name: string) => `community-attachment-card-${name}`,
  attachmentPreviewSheet: "community-attachment-preview-sheet",
  attachmentPreviewDownload: "community-attachment-preview-download",
  attachmentPreviewContent: "community-attachment-preview-content",
  mediaBlock: (name: string) => `community-media-block-${name}`,
  mediaPlay: (name: string) => `community-media-play-${name}`,
  mediaPlayer: (name: string) => `community-media-player-${name}`,
  mediaCollapse: (name: string) => `community-media-collapse-${name}`,
  mediaDownload: (name: string) => `community-media-download-${name}`,
  mediaRetry: (name: string) => `community-media-retry-${name}`,
  mediaStatus: (name: string) => `community-media-status-${name}`,
  codePreview: "community-code-preview",
  codePreviewLanguage: "community-code-preview-language",
  codePreviewCopy: "community-code-preview-copy",
  codePreviewWrap: "community-code-preview-wrap",
  codePreviewStatus: "community-code-preview-status",
  channelRow: (id: string) => `community-channel-row-${id}`,
  serverIcon: (id: string) => `community-server-icon-${id}`,
  dmRow: (id: string) => `community-dm-row-${id}`,
  memberRow: (id: string) => `community-member-row-${id}`,
  mentionOption: (id: string) => `community-mention-option-${id}`,
  mentionPopup: "community-mention-popup",
  mentionStatus: "community-mention-status",
  channelRefOption: (id: string) => `community-channel-ref-option-${id}`,
  channelRefPopup: "community-channel-ref-popup",
  channelRefStatus: "community-channel-ref-status",
  reactionAdd: (msgId: string) => `community-reaction-add-${msgId}`,
  reactionGroup: (msgId: string) => `community-reaction-group-${msgId}`,
  reactionChip: (msgId: string, emoji: string) =>
    `community-reaction-chip-${msgId}-${encodeURIComponent(emoji)}`,
  reactionDialog: (msgId: string) => `community-reaction-dialog-${msgId}`,
  reactionScroller: (msgId: string) => `community-reaction-scroller-${msgId}`,
  reactionFadeLeft: (msgId: string) => `community-reaction-fade-left-${msgId}`,
  reactionFadeRight: (msgId: string) => `community-reaction-fade-right-${msgId}`,
  reactionTab: (emoji: string) => `community-reaction-tab-${encodeURIComponent(emoji)}`,
  reactionMember: (userId: string) => `community-reaction-member-${userId}`,
  reactionEmpty: (msgId: string) => `community-reaction-empty-${msgId}`,
  messageShare: (msgId: string) => `community-message-share-${msgId}`,
  messageShareImage: (msgId: string, index: number) =>
    `message-share-image-${msgId}-${index}`,
  messageShareCopy: `community-message-share-copy`,
  threadIndicator: (msgId: string) => `community-thread-indicator-${msgId}`,
  get threadSplit() {
    return "community-thread-split" as const
  },
  get threadSplitParent() {
    return "community-thread-split-parent" as const
  },
  get threadSplitPanel() {
    return "community-thread-split-panel" as const
  },
  get threadSplitFullscreen() {
    return "community-thread-split-fullscreen" as const
  },
  get threadSplitClose() {
    return "community-thread-split-close" as const
  },
  railUnreadBadge: (serverId: string) => `community-rail-unread-badge-${serverId}`,
  // Forum post feed (ForumView). `forumThreadCard` is the whole clickable card;
  // `forumThreadTitle` / `forumThreadTitleText` expose the clamped title cluster
  // and its visible text; `forumThreadTagBtn` is the responsive tag-edit icon;
  // `forumThreadDeleteBtn` is the responsive delete icon; `forumThreadAvatars`
  // wraps the participant AvatarGroup; `forumTagChip` is a filter-bar tag chip.
  forumThreadCard: (id: string) => `community-forum-post-${id}`,
  forumSidebarThread: (id: string) => `community-forum-sidebar-thread-${id}`,
  forumThreadTitle: (id: string) => `community-forum-post-title-${id}`,
  forumThreadTitleText: (id: string) => `community-forum-post-title-text-${id}`,
  forumThreadSeq: (id: string) => `community-forum-post-seq-${id}`,
  forumThreadTagBtn: (id: string) => `community-forum-post-tag-btn-${id}`,
  forumThreadDeleteBtn: (id: string) => `community-forum-post-delete-btn-${id}`,
  forumThreadAvatars: (id: string) => `community-forum-post-avatars-${id}`,
  forumFilterBar: "community-forum-filter-bar",
  forumTagScroller: "community-forum-tag-scroller",
  forumTagFadeLeft: "community-forum-tag-fade-left",
  forumTagFadeRight: "community-forum-tag-fade-right",
  forumTagAll: "community-forum-tag-all",
  forumTagChip: (tag: string) => `community-forum-tag-chip-${tag}`,
  forumNewPost: "community-forum-new-post",
  forumPostList: "community-forum-post-list",
  inboxUnreadChannel: (id: string) => `community-inbox-unread-channel-${id}`,
  inboxUnreadChild: (id: string) => `community-inbox-unread-child-${id}`,
  inboxUnreadDm: (id: string) => `community-inbox-unread-dm-${id}`,
  channelRefPill: (id: string) => `community-channel-ref-pill-${id}`,
} as const
